# Generated by Django 4.2.21 on 2025-05-31 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^(Main|Dessert|Drink)$')]),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z0-9 ]+$'), django.core.validators.MinLengthValidator(2)]),
        ),
    ]
